### ISSUE TITLE
Newest version crashes MagiskHide + GoogleTurboApplication + makes SafetyNet to fail!

### ISSUE THREAD

**Issue by mscalindt** [Magisk-Modules-Repo/UniversalGMSDoze#1]
Ehm, yeah... And I can't provide logs...

LineageOS 15.1.
Android 8.1.0.

**Comment by gloeyisk** [comment]
Hello thanks for the report, but can you tell me be specific.
As you can see, everything fine on my side.
Screenshots attached.

![screenshot_magisk_manager_20181019-124850](https://user-images.githubusercontent.com/43908341/47199789-8d5feb80-d39d-11e8-8b46-e804d4b6659c.png)
![screenshot_settings_20181019-124832](https://user-images.githubusercontent.com/43908341/47199790-8d5feb80-d39d-11e8-9262-5f24271342a5.png)

**Comment by gloeyisk** [comment]
> 
> 
> Ehm, yeah... And I can't provide logs...
> 
> LineageOS 15.1.
> Android 8.1.0.

Hello thanks for the report, but can you tell me be specific?
As you can see, everything fine on my side.
Screenshots attached.
- [LineageOS 15.1 (8.1)](https://dl2.pushbulletusercontent.com/nLOQ4TBnajXaLz14bbaEjbbTOq0D9Nrm/Screenshot_Settings_20181019-124832.png)
- [Magisk Canary build](https://dl2.pushbulletusercontent.com/GQYHTcaXO1FnSEbZISJSYtLRjYR2oqug/Screenshot_Magisk_Manager_20181019-124850.png)
- [Doze module installed](https://dl2.pushbulletusercontent.com/H1vSBXXhv5NuNJ5JauD9PbT2cvj0IQWY/Screenshot_Magisk_Manager_20181019-125454.png)

**Comment by mscalindt** [comment]
You didn't give me enough time to answer back, lol.

1. Install your module (1.2.3 is the newest now I see) > restart > open Magisk Manager > open MagiskHide = Magisk Manager has stopped.
Still persist in 1.2.3 version.

2. com.google.turbo.app (similar package name, has to do something with doze) stopping.
Fixed in 1.2.3 version.

3. Google showing me something about my build (something about keys it was), hence making SafetyNet to fail!
Fixed in 1.2.3 version.

Now you only need to fix MagiskHide crashing. Maybe I was late to answer, but you closed the issue too early!

**Comment by gloeyisk** [comment]
> 
> 
> You didn't give me enough time to answer back, lol.
> 
>     1. Install your module (1.2.3 is the newest now I see) > restart > open Magisk Manager > open MagiskHide = Magisk Manager has stopped.
>        Still persist in 1.2.3 version.
> 
>     2. com.google.turbo.app (similar package name, has to do something with doze) stopping.
>        Fixed in 1.2.3 version.
> 
>     3. Google showing me something about my build (something about keys it was), hence making SafetyNet to fail!
>        Fixed in 1.2.3 version.
> 
> 
> Now you only need to fix MagiskHide crashing. Maybe I was late to answer, but you closed the issue too early!

Can you show me which Magisk you use? Anyway I'm sorry about closing the issue.
And also you can check the doze thread at xda to join my support group.

**Comment by mscalindt** [comment]
Magisk v17.1. Do you need logcat?

**Comment by mscalindt** [comment]
I for some reason didn't find the thread on XDA (or not sure if it's the right one).

**Comment by gloeyisk** [comment]
Uhm 17.1, it's ok it's not neccesary.
Can you try it with Magisk Canary? So far never facing those issues.

Here's the xda thread link
https://forum.xda-developers.com/apps/magisk/module-universal-gms-doze-t3853710/page2

**Comment by mscalindt** [comment]
I want to use normal version of Magisk, so I will just paste the log for crash (can't attach files on mobile, sorry).

I/17:10:28.832 am_finish_activity( 1272)
[0,194067158,32,com.topjohnwu.magisk/a.b,force-crash]
W/17:10:28.832 ActivityManager( 1272)
  Force finishing activity com.topjohnwu.magisk/a.b
I/17:10:28.830 am_crash( 1272)
[6810,0,com.topjohnwu.magisk,952647236,android.content.res.Resources$NotFoundException,String resource ID #0x7f0b0000,Resources.java,339]
E/17:10:28.829 AndroidRuntime( 6810)
	at java.lang.Thread.run(Thread.java:764)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.-$$Lambda$pw$XHhMVAPE5kAU9mXMZpnVj3lCL94.run(Unknown Source:2)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.pw.lambda$XHhMVAPE5kAU9mXMZpnVj3lCL94(Unknown Source:0)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.pw.b(Unknown Source:72)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.Collections.sort(Collections.java:201)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.ArrayList.sort(ArrayList.java:1470)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.Arrays.sort(Arrays.java:1498)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.TimSort.sort(TimSort.java:239)
E/17:10:28.829 AndroidRuntime( 6810)
	at java.util.TimSort.binarySort(TimSort.java:296)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.-$$Lambda$pw$tYxA4xTAL8_fjVmh1rciz2wYTqg.compare(Unknown Source:6)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.pw.lambda$tYxA4xTAL8_fjVmh1rciz2wYTqg(Unknown Source:0)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.pw.a(Unknown Source:18)
E/17:10:28.829 AndroidRuntime( 6810)
	at a.pw.a(Unknown Source:29)
E/17:10:28.829 AndroidRuntime( 6810)
	at android.content.res.Resources.getString(Resources.java:433)
E/17:10:28.829 AndroidRuntime( 6810)
	at android.content.res.Resources.getText(Resources.java:339)
E/17:10:28.829 AndroidRuntime( 6810)
android.content.res.Resources$NotFoundException: String resource ID #0x7f0b0000
E/17:10:28.829 AndroidRuntime( 6810)
Process: com.topjohnwu.magisk, PID: 6810
E/17:10:28.829 AndroidRuntime( 6810)
FATAL EXCEPTION: AsyncTask #1

**Comment by gloeyisk** [comment]
> 
> 
> I want to use normal version of Magisk, so I will just paste the log for crash (can't attach files on mobile, sorry).
> 
> I/17:10:28.832 am_finish_activity( 1272)
> [0,194067158,32,com.topjohnwu.magisk/a.b,force-crash]
> W/17:10:28.832 ActivityManager( 1272)
> Force finishing activity com.topjohnwu.magisk/a.b
> I/17:10:28.830 am_crash( 1272)
> [6810,0,com.topjohnwu.magisk,952647236,android.content.res.Resources$NotFoundException,String resource ID #0x7f0b0000,Resources.java,339]
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.lang.Thread.run(Thread.java:764)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.-$$Lambda$pw$XHhMVAPE5kAU9mXMZpnVj3lCL94.run(Unknown Source:2)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.pw.lambda$XHhMVAPE5kAU9mXMZpnVj3lCL94(Unknown Source:0)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.pw.b(Unknown Source:72)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.Collections.sort(Collections.java:201)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.ArrayList.sort(ArrayList.java:1470)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.Arrays.sort(Arrays.java:1498)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.TimSort.sort(TimSort.java:239)
> E/17:10:28.829 AndroidRuntime( 6810)
> at java.util.TimSort.binarySort(TimSort.java:296)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.-$$Lambda$pw$tYxA4xTAL8_fjVmh1rciz2wYTqg.compare(Unknown Source:6)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.pw.lambda$tYxA4xTAL8_fjVmh1rciz2wYTqg(Unknown Source:0)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.pw.a(Unknown Source:18)
> E/17:10:28.829 AndroidRuntime( 6810)
> at a.pw.a(Unknown Source:29)
> E/17:10:28.829 AndroidRuntime( 6810)
> at android.content.res.Resources.getString(Resources.java:433)
> E/17:10:28.829 AndroidRuntime( 6810)
> at android.content.res.Resources.getText(Resources.java:339)
> E/17:10:28.829 AndroidRuntime( 6810)
> android.content.res.Resources$NotFoundException: String resource ID #0x7f0b0000
> E/17:10:28.829 AndroidRuntime( 6810)
> Process: com.topjohnwu.magisk, PID: 6810
> E/17:10:28.829 AndroidRuntime( 6810)
> FATAL EXCEPTION: AsyncTask #1

I though you compressed it =D
